version: '2'
services:
  base:
    build: .
    restart: on-failure

  emailer:
    extends: base
    command: node emailer/server.js
    ports:
      - 80:5000

  email-mailgun-service:
    extends: base
    command: node services/email-mailgun-service.js
    environment:
      MAILGUN_API_KEY=${MAILGUN_API_KEY}
      MAILGUN_DOMAIN=${MAILGUN_DOMAIN}

  email-sendinblue-service:
    extends: base
    command: node services/email-sendinblue-service.js
    environment:
      SENDINBLUE_V2_API_KEY=${SENDINBLUE_V2_API_KEY}

  logger-service:
    extends: base
    command: node services/logger-service.js
